### ISSUE TITLE
Feature Request: Custom seed per prompt

### ISSUE THREAD

**Issue by udside** [feffy380/prompt-morph#2]
Thank you for this script its great!
I see there is intention to add seed travel to the script?
And I was wondering if it would be possible to add a custom seed per prompt?
Something like in the Animator script (https://github.com/Animator-Anon/Animator)
Thanks

**Comment by feffy380** [comment]
The latest commit adds seed travel. You can specify a seed with the format `Seed | Prompt` or just `Prompt` to reuse the previous seed (no seed travel).

I have to admit the transitions aren't very smooth, since the script is based on prompt weighting and not img2img like with Animator.
